/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignRouteImport } from './routes/design'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as V2RunsRunIdIndexRouteImport } from './routes/v2.runs.$runId.index'
import { Route as V2RunsRunIdStageIdRouteImport } from './routes/v2.runs.$runId.$stageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const V2RunsRunIdIndexRoute = V2RunsRunIdIndexRouteImport.update({
  id: '/v2/runs/$runId/',
  path: '/v2/runs/$runId/',
  getParentRoute: () => rootRouteImport,
} as any)
const V2RunsRunIdStageIdRoute = V2RunsRunIdStageIdRouteImport.update({
  id: '/v2/runs/$runId/$stageId',
  path: '/v2/runs/$runId/$stageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/v2/runs/$runId/$stageId': typeof V2RunsRunIdStageIdRoute
  '/v2/runs/$runId/': typeof V2RunsRunIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/v2/runs/$runId/$stageId': typeof V2RunsRunIdStageIdRoute
  '/v2/runs/$runId': typeof V2RunsRunIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/v2/runs/$runId/$stageId': typeof V2RunsRunIdStageIdRoute
  '/v2/runs/$runId/': typeof V2RunsRunIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/runs/$runId'
    | '/v2/runs/$runId/$stageId'
    | '/v2/runs/$runId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/runs/$runId'
    | '/v2/runs/$runId/$stageId'
    | '/v2/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/runs/$runId'
    | '/v2/runs/$runId/$stageId'
    | '/v2/runs/$runId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  V2RunsRunIdStageIdRoute: typeof V2RunsRunIdStageIdRoute
  V2RunsRunIdIndexRoute: typeof V2RunsRunIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/runs/$runId/': {
      id: '/v2/runs/$runId/'
      path: '/v2/runs/$runId'
      fullPath: '/v2/runs/$runId/'
      preLoaderRoute: typeof V2RunsRunIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/runs/$runId/$stageId': {
      id: '/v2/runs/$runId/$stageId'
      path: '/v2/runs/$runId/$stageId'
      fullPath: '/v2/runs/$runId/$stageId'
      preLoaderRoute: typeof V2RunsRunIdStageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  V2RunsRunIdStageIdRoute: V2RunsRunIdStageIdRoute,
  V2RunsRunIdIndexRoute: V2RunsRunIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
